name: Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'

permissions:
  contents: read
  checks: write
  id-token: write

env:
  JAVA_VERSION: "17"
  JAVA_DISTR: 'corretto'

jobs:
  assemble_apk:
    name: "📦 Assemble APKs"    
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JAVA_DISTR }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Assemble debug APKs
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: packageDistributionForCurrentOS

      - name: Upload APKs
        uses: actions/upload-artifact@v3
        with:
          name: artifacts.zip
          path: |
            desktop/build/compose/binaries/main
            newquiz_uploads/build/outputs/aar
